# Generated by Django 5.0.2 on 2024-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_status',
            field=models.SmallIntegerField(choices=[(0, '승인'), (1, '거절'), (-1, '탈퇴'), (2, '대기')], default=0),
        ),
    ]
