# Generated by Django 5.0.2 on 2024-03-03 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='notification/%Y/%m/%d')),
            ],
            options={
                'db_table': 'tbl_notification_file',
            },
        ),
    ]
