# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationFile',
        ),
    ]
