# Generated by Django 5.0.2 on 2024-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
