# Generated by Django 5.0.2 on 2024-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitionfile',
            name='download_path',
            field=models.ImageField(default=1, upload_to='exhibition_down/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitionfile',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
