# Generated by Django 5.0.2 on 2024-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_exhibitionfile_exhibitionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
