# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_exhibitionfile_exhibitionlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionlike',
            name='like',
        ),
        migrations.DeleteModel(
            name='ExhibitionFile',
        ),
        migrations.DeleteModel(
            name='ExhibitionLike',
        ),
    ]
