# Generated by Django 5.0.2 on 2024-03-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_exhibition_exhibition_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionfile',
            name='exhibition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exhibition.exhibition'),
            preserve_default=False,
        ),
    ]
