# Generated by Django 5.0.2 on 2024-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareMember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemember',
            name='share_member_status',
            field=models.SmallIntegerField(choices=[(0, '결제'), (1, '환불'), (-1, '대기')], default=0),
        ),
    ]
