# Generated by Django 5.0.2 on 2024-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareMember', '0002_alter_sharemember_share_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemember',
            name='share_member_status',
            field=models.SmallIntegerField(choices=[(0, '결제'), (1, '환불')], default=0),
        ),
    ]
