# Generated by Django 5.0.2 on 2024-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_school_email',
            field=models.CharField(default='<EMAIL>', max_length=50),
        ),
    ]
