# Generated by Django 5.0.2 on 2024-03-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_memberfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(max_length=20),
        ),
    ]
