# Generated by Django 5.0.2 on 2024-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='MemberFile',
        ),
    ]
