# Generated by Django 5.0.2 on 2024-03-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_memberfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberFile',
        ),
    ]
