# Generated by Django 5.0.2 on 2024-03-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_delete_memberfile'),
        ('member', '0008_memberfile'),
    ]

    operations = [
    ]
