# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityfile_communitylike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitylike',
            name='like',
        ),
        migrations.DeleteModel(
            name='CommunityFile',
        ),
        migrations.DeleteModel(
            name='CommunityLike',
        ),
    ]
