# Generated by Django 5.0.2 on 2024-03-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_community_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfile',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='community.community'),
            preserve_default=False,
        ),
    ]
