# Generated by Django 5.0.2 on 2024-05-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.SmallIntegerField(choices=[(0, '공부'), (1, '친목'), (2, '수다'), (3, '공모전/대회')]),
        ),
    ]
