# Generated by Django 5.0.2 on 2024-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_status',
            field=models.SmallIntegerField(choices=[(1, '사용 완료'), (2, '사용 취소'), (3, '충전 완료'), (4, '충전 취소'), (5, '대기 중')]),
        ),
    ]
