# Generated by Django 5.0.2 on 2024-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_alter_point_point_alter_point_point_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point_status',
            field=models.SmallIntegerField(choices=[(1, '사용'), (2, '충전'), (3, '적립')]),
        ),
    ]
