# Generated by Django 5.0.2 on 2024-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_depth',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_group_id',
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(),
        ),
    ]
