# Generated by Django 5.0.2 on 2024-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
