# Generated by Django 5.0.2 on 2024-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
