# Generated by Django 5.0.2 on 2024-03-05 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_review_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfile',
            name='path',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='review/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
