# Generated by Django 5.0.2 on 2024-03-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewfile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfile',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='review.review'),
            preserve_default=False,
        ),
    ]
