# Generated by Django 5.0.2 on 2024-03-02 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_title', models.CharField(max_length=30)),
                ('place_content', models.CharField(max_length=300)),
                ('place_points', models.BigIntegerField(default=1000, null=True)),
                ('place_order_status', models.BooleanField(default=False)),
                ('place_review_rating', models.FloatField(default=0.0)),
                ('place_image_file', models.ImageField(upload_to='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school')),
            ],
            options={
                'db_table': 'tbl_place',
                'ordering': ['-id'],
            },
        ),
    ]
