# Generated by Django 5.0.2 on 2024-03-04 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('like', '0001_initial'),
        ('place', '0001_initial'),
        ('point', '0001_initial'),
        ('review', '0002_reviewfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceLike',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='like.like')),
            ],
            options={
                'db_table': 'tbl_place_like',
            },
        ),
        migrations.CreateModel(
            name='PlacePoints',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='point.point')),
            ],
            options={
                'db_table': 'tbl_place_points',
            },
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='review.review')),
            ],
            options={
                'db_table': 'tbl_place_review',
            },
        ),
        migrations.CreateModel(
            name='PlaceFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='place/%Y/%m/%d')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.place')),
            ],
            options={
                'db_table': 'tbl_place_file',
            },
        ),
    ]
