# Generated by Django 5.0.2 on 2024-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_placelike_placepoints_placereview_placefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
