# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_placefile_placelike_placepoints_placereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placelike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='placepoints',
            name='points',
        ),
        migrations.RemoveField(
            model_name='placereview',
            name='review',
        ),
        migrations.DeleteModel(
            name='PlaceFile',
        ),
        migrations.DeleteModel(
            name='PlaceLike',
        ),
        migrations.DeleteModel(
            name='PlacePoints',
        ),
        migrations.DeleteModel(
            name='PlaceReview',
        ),
    ]
