# Generated by Django 5.0.2 on 2024-03-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_place_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placefile',
            name='post',
        ),
    ]
