# Generated by Django 5.0.2 on 2024-03-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_placefile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereview',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='place.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placefile',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.place'),
        ),
    ]
