# Generated by Django 5.0.2 on 2024-03-02 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('onelab_title', models.CharField(max_length=50)),
                ('onelab_content', models.CharField(max_length=20)),
                ('onelab_participate_url', models.CharField(max_length=100)),
                ('onelab_participate_group_id', models.IntegerField()),
                ('onelab_status', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.university')),
            ],
            options={
                'db_table': 'tbl_onelab',
                'ordering': ['-id'],
            },
        ),
    ]
