# Generated by Django 5.0.2 on 2024-03-13 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('like', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('onelab_title', models.CharField(max_length=50)),
                ('onelab_content', models.CharField(max_length=20)),
                ('onelab_participate_url', models.CharField(max_length=100)),
                ('onelab_participate_group_id', models.IntegerField()),
                ('onelab_status', models.BooleanField(default=True)),
                ('onelab_post_status', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.university')),
            ],
            options={
                'db_table': 'tbl_onelab',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OneLabBannerFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='onelab_banner/%Y/%m/%d')),
                ('onelab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onelab.onelab')),
            ],
            options={
                'db_table': 'tbl_onelab_banner_file',
            },
        ),
        migrations.CreateModel(
            name='OneLabFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='onelab/%Y/%m/%d')),
                ('onelab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onelab.onelab')),
            ],
            options={
                'db_table': 'tbl_onelab_file',
            },
        ),
        migrations.CreateModel(
            name='OneLabLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='like.like')),
            ],
            options={
                'db_table': 'tbl_onelab_like',
            },
        ),
    ]
