# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelab', '0002_onelabbannerfile_onelabfile_onelablike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onelabfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='onelablike',
            name='like',
        ),
        migrations.DeleteModel(
            name='OneLabBannerFile',
        ),
        migrations.DeleteModel(
            name='OneLabFile',
        ),
        migrations.DeleteModel(
            name='OneLabLike',
        ),
    ]
