# Generated by Django 5.0.2 on 2024-03-04 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
        ('onelab', '0002_onelabbannerfile_onelabfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLabLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='like.like')),
            ],
            options={
                'db_table': 'tbl_onelab_like',
            },
        ),
    ]
