# Generated by Django 5.0.2 on 2024-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelab', '0003_onelablike'),
    ]

    operations = [
        migrations.AddField(
            model_name='onelab',
            name='onelab_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
