# Generated by Django 5.0.2 on 2024-03-02 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('like', '0001_initial'),
        ('onelab', '0003_remove_onelabfile_file_remove_onelablike_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLabBannerFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='onelab_banner/%Y/%m/%d')),
            ],
            options={
                'db_table': 'tbl_onelab_banner_file',
            },
        ),
        migrations.CreateModel(
            name='OneLabFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='onelab/%Y/%m/%d')),
            ],
            options={
                'db_table': 'tbl_onelab_file',
            },
        ),
        migrations.CreateModel(
            name='OneLabLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='like.like')),
            ],
            options={
                'db_table': 'tbl_onelab_like',
            },
        ),
    ]
