# Generated by Django 5.0.2 on 2024-03-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelab', '0004_onelab_onelab_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onelabbannerfile',
            name='onelab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='onelab.onelab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onelabfile',
            name='onelab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='onelab.onelab'),
            preserve_default=False,
        ),
    ]
