# Generated by Django 5.0.2 on 2024-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='high_school_member_birth',
            field=models.DateField(default='2008-01-01'),
        ),
    ]
