# Generated by Django 5.0.2 on 2024-03-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highschool', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highschool',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='id',
        ),
        migrations.AlterField(
            model_name='highschool',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='member.member'),
        ),
    ]
