# Generated by Django 5.0.2 on 2024-03-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeMember', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemember',
            name='place_member_name',
        ),
    ]
