# Generated by Django 5.0.2 on 2024-03-03 01:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('university_member_school', models.CharField(max_length=100)),
                ('university_member_major', models.CharField(max_length=100)),
                ('university_member_points', models.BigIntegerField(default=0)),
                ('university_member_birth', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_university',
                'ordering': ['-id'],
            },
        ),
    ]
