# Generated by Django 5.0.2 on 2024-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_member_birth',
            field=models.DateField(default='2005-01-01'),
        ),
    ]
