# Generated by Django 5.0.2 on 2024-03-03 01:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('share_title', models.CharField(max_length=30)),
                ('share_content', models.CharField(max_length=2000)),
                ('share_points', models.BigIntegerField(default=1000, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.university')),
            ],
            options={
                'db_table': 'tbl_share',
                'ordering': ['id'],
            },
        ),
    ]
