# Generated by Django 5.0.2 on 2024-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_sharefile_sharelike_sharepoints_sharereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
