# Generated by Django 5.0.2 on 2024-03-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_share_share_choice_grade_share_share_choice_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepoints',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='share.share'),
            preserve_default=False,
        ),
    ]
