# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_sharefile_sharelike_sharepoints_sharereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='sharepoints',
            name='points',
        ),
        migrations.RemoveField(
            model_name='sharereview',
            name='share',
        ),
        migrations.DeleteModel(
            name='ShareFile',
        ),
        migrations.DeleteModel(
            name='ShareLike',
        ),
        migrations.DeleteModel(
            name='SharePoints',
        ),
        migrations.DeleteModel(
            name='ShareReview',
        ),
    ]
