# Generated by Django 5.0.2 on 2024-03-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_share_share_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='share.share'),
            preserve_default=False,
        ),
    ]
